# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
resources:
  repositories:
    - repository: CheckmarxYamlTemplates
      type: git
      name: DevSecOps/CheckmarxYamlTemplates
      ref: master
  
variables:
  cxTeam: 'CxServer\JornadaIngresso\JIFU'
  cxProjectName: '$(Build.DefinitionName)'


steps:
  - template: NightlyAsync.AllInOne.yaml@CheckmarxYamlTemplates
