name: Fluid Attacks

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
jobs:
  forces:
    runs-on: ubuntu-latest
    container:
      image: fluidattacks/forces:latest
      env:
        TOKEN:
        REPO_NAME:
    steps:
      - name: Run Agent check
        run: forces --token "${eyJhbGciOiJSUzUxMiJ9.eyJjaXBoZXJ0ZXh0IjoiRmNFMXM3dDV3VzNEVTRyT2dTVkpuVU40OVRERUt1VGFTT1VTOFBmVW9LeXBjSnBLMjNrNUhoYi1ZVXg3Mmc4ZGpENjZQeUpad0ttcU1BazBoWjFCM3JRX0gwVDU3bDhPa280Tnp3T0diVlVxN3NhTVp0eTlCd295bUNvUmh1UTJxMTFleXF4dlktdDloeEZnTTM2T0hhVTFGaTQ5LU0tYlZRODRLNEduU3ZnVkh3UVNTSnNsdUk3RS1zWmYiLCJlbmNyeXB0ZWRfa2V5IjoiM0lLRzhUOThodDJ4aVJjeTZ5Z3dZNlM1QWVHcEZSVEJ5RzhYQnVlNnhSYyIsImV4cCI6MTgwMTA3MDA0NywiaGVhZGVyIjp7Iml2IjoiQldNNEdHbnhvWW5PdVdpdyIsInRhZyI6IjB4WmdmQll0ZUV5dFdobnM0Tmpsc3cifSwiaXYiOiI0UGdTSjd6aUhFMGN6VU5EIiwicHJvdGVjdGVkIjoiZXlKaGJHY2lPaUpCTWpVMlIwTk5TMWNpTENKbGJtTWlPaUpCTWpVMlIwTk5JbjAiLCJzdWIiOiJhcGlfdG9rZW4iLCJ0YWciOiIxNlhRMS1HZnBicGk4TS1rU2RUX2xRIn0.OOC4Vx4_U4cYRpcKFHDejAJ4APHoh5756sW6ro26Eh-UzMQtNwD0eLcVVYzgaZYJ7cOzv170L0KxYp0pDkVkPyCLn8A_Vl9wU90p4entf-3MmSTOprnpUReIp6Ce3YuiDswHnM4Cirh5o1OP-1oVXqwjDqpM60Gh_r0ZB2DFG71vQC5GRdWKkbW3PhpxTLmiWMx-LuMbjkMrtd7fNYFAcWgVFPYtAa0yU2igs8eFBpNnmPLFbrHy9oFyqgaxRxp4tpFdmMFzvx1WEifjr5ztkt6BsZgu9A0fcMfufyav8tZXptUngGXI__PwlKRSfSOXAWKDyLvU3PlalQuOt_R7Tg}" --strict --repo-name ${Nova-8_JavaVulnerableLab-SCS-TechSales}
