name: Fluid Attacks

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
jobs:
  forces:
    runs-on: ubuntu-latest
    container:
      image: fluidattacks/forces:latest
      env:
        FLUID_TOKEN: ${{ secrets.FLUID_TOKEN }}
    steps:
      - name: Run Agent check
        run: forces --token ${FLUID_TOKEN} --strict
